###
# register new users
POST http://localhost:4000/v1/auth/register
Content-Type: application/json

{
    "username":"lance",
    "email":"lancelot@gmail.com",
    "password":"@Lance25"
}

###
# login existing users
POST http://localhost:4000/v1/auth/login
Content-Type: application/json

{
    "usernameOrEmail":"lancelot@gmail.com",
    "password":"@Lance25"
}

###
# forgot password
POST http://localhost:4000/v1/auth/change-password/0b6ecb34-25d9-11f1-878e-aa9483c2e19b
Content-Type: application/json

{
    "newPassword": "@Lance25"
}
