###
# register new users
POST http://localhost:4000/v1/auth/register
Content-Type: application/json

{
    "username":"lance",
    "email":"lancelot@gmail.com",
    "password":"@Lance25"
}

###
# login existing users
POST http://localhost:4000/v1/auth/login
Content-Type: application/json

{
    "usernameOrEmail":"marcus@gmail.com",
    "password":"@Lance25"
}

###
# forgot password
POST http://localhost:4000/v1/auth/forgot-password
Content-Type: application/json

{
    "usernameOrEmail": "marcus@gmail.com"
}
