#!/usr/bin/env bash

db="maktaba"
echo "building the $db database"

# make the complete db file but it first removes it if it exists
rm db.sql
touch db.sql

# loop through base files, appending to the complete one
for file in ./schema/{tables.sql,stored_procedures.sql,views.sql,triggers.sql}; do
    cat $file >> db.sql
done

# build the entire db
mysql -u root -p < db.sql > output.tab
