#!/usr/bin/env bash

database="maktaba"
echo "drop $database database? [y/n] "
read choice

if [[ "$choice" == "y" ]]; then
    echo " "
    echo "deleting $database database.."
    mysql -u root -p < drop.sql > output.tab
elif [[ "$choice" == "n" ]]; then
    echo " "
    echo "aborting deletion..."
else
    echo "invalid input. try again?"
fi
